### ISSUE TITLE
Please check your SteamIDS varible

### ISSUE THREAD

**Issue by Inadequado4192** [ErenKrt/SteamWorkshopDownloader.js#1]
This doesn't seem to work when using `DownClient.GetInfo("753498552")`. What am I doing wrong?

**Comment by ErenKrt** [comment]
Code broken after updated using API.  I will update soon.

**Comment by ErenKrt** [comment]
Hello, i updated repo. You can use with global and normal.
If you want global,
`npm i steamworkshopdownloader -g`
After that go your location.
`steamwd 2712258978` OR `steamwd 2712258978 2712258977 [...]` 

If you want normal, just check test folder.
