### ISSUE TITLE
electron

### ISSUE THREAD

**Issue by Inadequado4192** [ErenKrt/SteamWorkshopDownloader.js#2]
Hello, the package works fine if you just run a separate `js` file, but if you use it in `electron` then there are errors and I do not know how to fix them (I am new to `electron`). if I try to call `MyDown.Download` in the main file (via `ipcMain`), it returns me the following
```js
{
  success: false,
  data: [],
  message: 'Cant fetch workshop(s) item(s).'
}
```

If I call `MyDown.Download` in the window, then the following will happen:
![image](https://user-images.githubusercontent.com/47379767/157132673-494d1727-23e3-4c1e-9f22-0e63f1e0c109.png)

> I hope I explained the problem correctly. I know very little about `electron' and there is no way I can solve this problem on my own and I have no one to ask but here :c

**Comment by ErenKrt** [comment]
hello, thank you for your feedback. Electron can do things according to normal node js. I will try it on my own electron client and solve the error asap.

**Comment by ErenKrt** [comment]
Hello again. First of all dont use script on front-end with electron nodeIntegration support. Because when you use on front-end side API request failed of tried set user agent. Chromium not support change user-agent on requests. You can use event bus feature of electron.

Here is example;

// Backend side

```
const {ipcMain} = require('electron')
ipcMain.on("download",async (event,data)=>{
  var spl= data.ids.split(' ');
  var MyIds=[];
  for (let i = 0; i < spl.length; i++) {
    MyIds.push(spl[i]);
  }
  event.returnValue=await MyDownloaderClient.Download(MyIds,data.path);;
});
```

// Frontend side

```
const { ipcRenderer } = require('electron');

document.querySelector("#down").addEventListener("click",()=>{
    var Data= ipcRenderer.sendSync("download",{
        ids:document.querySelector("#workshopids").value,
        path:"./"
    });

    console.log(Data);
});
```

**Comment by Inadequado4192** [comment]
So I have to set `nodeIntegration` to `false` to make it work? Right now my code is the same as yours, but with the same error:
```js
{
  success: false,
  data: [],
  message: 'Cant fetch workshop(s) item(s).'
}
```

**Comment by ErenKrt** [comment]
i will check again.

**Comment by Inadequado4192** [comment]
I rewrote the program with `nodeIntegration` disabled, but the problem remains :c

**Comment by ErenKrt** [comment]
Error fixed with new publish. Can u try again ?

**Comment by Inadequado4192** [comment]
It didn't seem to work. Maybe I'm doing something wrong?
```js
[Function: wrap] {
  request: [Function: wrap],
  getUri: [Function: wrap],
  delete: [Function: wrap],
  get: [Function: wrap],
  head: [Function: wrap],
  options: [Function: wrap],
  post: [Function: wrap],
  put: [Function: wrap],
  patch: [Function: wrap],
  defaults: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [Function: xhrAdapter],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 0,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    validateStatus: [Function: validateStatus],
    headers: {
      common: [Object],
      delete: {},
      get: {},
      head: {},
      post: [Object],
      put: [Object],
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/97.0.4692.99 Safari/537.36 OPR/83.0.4254.62'
    },
    baseURL: 'https://node01.steamworkshopdownloader.io/prod/api/'
  },
  interceptors: {
    request: InterceptorManager { handlers: [] },
    response: InterceptorManager { handlers: [] }
  },
  create: [Function: create]
}
{
  success: false,
  data: [],
  message: 'Cant fetch workshop(s) item(s).'
}
```

**Comment by ErenKrt** [comment]
Can you send your download code line with workshop ids.

**Comment by Inadequado4192** [comment]
`electron.ts`
```ts
ipcMain.on("test", async (e, a) => {
    let d = new Downloader();
    console.log(await d.Download([753498552], path.join(__dirname, "/temp/")));
});
```

`preload.ts`
```ts
ipcRenderer.sendSync("test");
```

**Comment by ErenKrt** [comment]
Dont forget remove and reinstall steamworkshopdownloader.

```
npm remove steamworkshopdownloader
npm install steamworkshopdownloader
```

index.ts:
```
import { app, BrowserWindow } from 'electron';
import { ipcMain } from 'electron';
import { Downloader } from 'steamworkshopdownloader'
import * as path from 'path';

ipcMain.on("download", async (e, a) => {
    let d = new Downloader();
    console.log(await d.Download([753498552], path.join(__dirname, "./down/")));
});

app.on('ready', () => {
    console.log('App is ready');

    const win = new BrowserWindow({
        width: 600,
        height: 400,
        webPreferences:{
            nodeIntegration:true,
            preload: path.join(__dirname, 'preload.js')
        }
    });

    const indexHTML = path.join(__dirname + '/index.html');
    
    win.loadFile(indexHTML).then(() => {}).catch(e => console.error(e));
});
```


Preload.ts:

```
const { ipcRenderer } = require('electron');
ipcRenderer.sendSync("download");

```

**Comment by Inadequado4192** [comment]
Hmm... I did as you said, but it didn't work. So I decided to create a separate project with your code and it worked. Looks like something in my code is preventing it :c
I will look for it, thank you :)

**Comment by Inadequado4192** [comment]
I think I found what was wrong. All because of `webpack`.

**Comment by ErenKrt** [comment]
I'm not using webpack on my electron test project. Yeah thats make sense. When use webpack on electron make some errors. You can use webpack only for UI side.
If you found a solution, you can close this issue. Thanks for feedback again.

**Comment by Inadequado4192** [comment]
Thank you so much for your help!
