### ISSUE TITLE
This does not search for item dependencies?

### ISSUE THREAD

**Issue by DimaSheiko** [ErenKrt/SteamWorkshopDownloader.js#3]
Hi, I would like to know if this script looks for the dependencies of what I am downloading and also downloads them, that is, if I want to download a collection then it would be ideal to download all the items in the collection and also the dependencies of each item.

**Comment by ErenKrt** [comment]
Hi, thanks for your feedback. If you tried to download with the global command, unfortunately it did not give you what you wanted. The global command simply downloads according to the given IDs. I wanted to keep the global command simple.  Beacuse I will be change the structure in the future.

I'm sharing code with you for download all workshop items and all dependencies of items.
Code collect all workshop items and dependencies id after that push all ids to download.

```javascript
var {Downloader}= require('steamworkshopdownloader');
var MyDown= new Downloader();

async function GetAllIDS(Workshop){
    var WorkShopIDs = [];

    if(Workshop.fileType!=2){
        WorkShopIDs.push(Workshop.id);
    }

    if(Workshop.childs!=null && Workshop.childs.length > 0){
        for(const SingleChild of Workshop.childs){
            var ChildInfo= await MyDown.Info([SingleChild.id]);
            var ChildsOfChild=await GetAllIDS(ChildInfo.data[0]);
            for(const SingleChildOfChilds of ChildsOfChild){
                WorkShopIDs.push(SingleChildOfChilds);
            }
        }
    }

   return WorkShopIDs;
}

(async function(){
    var Down= await MyDown.Info([2276588418]); // your collection id or workshop item

    if(Down.data==null || Down.data.length <= 0){
        console.log("Cant find workshop infos !!!");
    }
    var AllIDS=[];

    for(const SingleWorkShop of Down.data){
        AllIDS= AllIDS.concat(await GetAllIDS(SingleWorkShop));
    }

    var Uniqs= AllIDS.filter((item, i, ar) => ar.indexOf(item) === i);

    await MyDown.Download(Uniqs,"./downs/");
})()
```

**Comment by ErenKrt** [comment]
Hello again, this feature added on version of 3. You can use "-d" option in your command.

**Comment by DimaSheiko** [comment]
This is awesome!!! Thank you!

The first download I tried did not work for me. I tried with other items from the workshop and it worked fine.
`steamwd 2782791830 -d` dont work for me 
`1552611740` also does not work
`1265936057` This one seems to work partially, it downloads some items and not others, my console is going crazy with this collection. Tried a second time and got the error `TypeError: Cannot read property 'IDS' of undefined`

**Comment by ErenKrt** [comment]
The api I use does not return some things as I want. That's why such errors can occur. Thank you for creating an issue. I will solve it as soon as possible.

**Comment by ErenKrt** [comment]
Hello again, dont forget update this package for 3.1.0
I made the update by examining the ids one by one.

2782791830 / 1552611740 = Make infinity dependencies request
1265936057 = Have so many items, console cant show at same time

**Comment by DimaSheiko** [comment]
This is absolutely great! Thank you so much for this! It now works great with the tests I have done. You rocked it.
Thank you so much again
