### ISSUE TITLE
Progress Event

### ISSUE THREAD

**Issue by Inadequado4192** [ErenKrt/SteamWorkshopDownloader.js#4]
Hello, it's me again. I saw that there is a message in the console when loading, and I would like to get these values. Is it possible to add a `progress` event?

![image](https://user-images.githubusercontent.com/47379767/158361681-de3b0100-bde8-48ae-9e48-764c9824eb98.png)

> And it would be nice to be able to disable these notifications in the console :)

**Comment by ErenKrt** [comment]
With an update, I will separate downloading and fetch zip from server. So I can give progress event.  And you can get the progress event by writing your own download system.

**Comment by ErenKrt** [comment]
Hello again, I continue to develop the new version on the beta branch. Now you can build and use it if you want, in a way that you can callback and give the download url of the file. The new version will be finished in 1-2 weeks i guess.

**Comment by ErenKrt** [comment]
Hello again. This feature added on version of 3. Please check example.

**Comment by Inadequado4192** [comment]
Everything seems to have become very unclear :)
Now the module `steamworkshopdownloader` is not found, the example uses `nodejs-file-downloader`, and how to get the parameter for the property `url` I do not quite understand. The example uses this part:
```ts
import { Client } from '../src/api'
import { FileStatus } from '../src/api/types'
import { makeDownloadUrl } from '../src/api/utils'
```

> I may be missing something again :)

**Comment by ErenKrt** [comment]
Dont forget reinstall this package.
Here is your example code.

```
const { Client } = require('steamworkshopdownloader');
// OR
import { Client } from 'steamworkshopdownloader'


var MyClient= new Client();
MyClient.getItems([274974442]).then(data=>{
    console.log(data);
})

```

**Comment by Inadequado4192** [comment]
On the 3rd reinstall it all worked, looks like I have some problems again, sorry :)

**Comment by ErenKrt** [comment]
Still if you have any problem can you open new issuie ?

**Comment by Inadequado4192** [comment]
I haven't checked it yet, but if there are any errors/questions, I'll create one)
