### ISSUE TITLE
Any chance that the downloads can be organized by folder?

### ISSUE THREAD

**Issue by DimaSheiko** [ErenKrt/SteamWorkshopDownloader.js#5]
I play cities skylines, and the workshop of this game is full of collections and assets that require other assets and mods and in turn those mods and others and so on.

Basically it is divided into two types. The mods and assets, so when you download a collection that has many items of assets and mods are downloaded all in the same folder, but to install them in the game is necessary to separate them into two folders, ./Mods and ./Assets for example, to separate them basically you have to go folder by folder and check what type is and move it to the folder within the game that corresponds, this is done automatically if you have the game purchased on steam and you subscribe to a collection.

It would be great if it could be done with this downloader to organize the folders automatically. I see that other games do not follow this pattern of assets/mods and therefore I see it complicated to deduce unless it is created by the category of the file, it would be easier, but still not automatic.

What do you think? Would it be possible?

**Comment by ErenKrt** [comment]
Hello, first of all, thank you very much for your interest.

I'm currently doing what you want on the web version. On this version, you will be able to copy or move the file layout as you wish. There is only one problem, the api I use does not download the workshops that need to be purchased for the game to be downloaded. But I will try to solve it.

**Comment by DimaSheiko** [comment]
Is the web version currently available for testing?

**Comment by ErenKrt** [comment]
Im sorry, not yet. You can follow web progress on beta branch.
