### ISSUE TITLE
Download assets from different games

### ISSUE THREAD

**Issue by DimaSheiko** [ErenKrt/SteamWorkshopDownloader.js#6]
Hi, I have tried to download a collection of assets, and I have had problems in the console, I tried several times, and sometimes the pointer keeps blinking.

I also noticed that it downloads assets from other games for example `949252631` while I am downloading `881552391`. I have inspected all the assets in the collection to see if any of them required the other game's asset by mistake, but I didn't get any.

![image](https://user-images.githubusercontent.com/67640628/162584663-a5a14557-06ae-4676-8795-11e111402e11.png)

If I wanted to see the errors I would have to use it as [Import Using](https://github.com/ErenKrt/SteamWorkshopDownloader.js#import-using)?

**Comment by ErenKrt** [comment]
Hi, this error can happen because of "steamworkshopdownloader.io". Also, this is not an app bug. That's why you won't be able to catch it as an error even when using with "using". If you want to debug, you can use "using" with to see why it pulls different things.

**Comment by DimaSheiko** [comment]
Oh, I understand. So there's nothing to do?

**Comment by DimaSheiko** [comment]
I downloaded all the items in the collection individually and everything worked fine, without downloading from other games.

**Comment by ErenKrt** [comment]
Of course there is a solution. I'll try to fix it with an update soon.
