### ISSUE TITLE
Request failed with status code 504 | 502

### ISSUE THREAD

**Issue by Inadequado4192** [ErenKrt/SteamWorkshopDownloader.js#7]
Hi, why do I sometimes get these errors when I download a file: `Request failed with status code 504`, `Request failed with status code 502` ? How can I fix it?

**Comment by ErenKrt** [comment]
Hi, "steamworkshopdownloader.io" is experiencing corruptions because the api url is changed frequently. I updated it to new. You can test it.

**Comment by Inadequado4192** [comment]
Looks like everything works now, thanks)
