### ISSUE TITLE
TypeError: Cannot read property 'title_disk_safe' of undefined

### ISSUE THREAD

**Issue by DimaSheiko** [ErenKrt/SteamWorkshopDownloader.js#8]
Greetings! I wanted to use this tool that has saved me on several occasions and when I tried it I got a new error, it seems that the api that you are using is returning timeout in some occasions. I am not sure if it is my provider or not, but I have used VPN to test and it keeps giving the same error.

```
Request failed with status code 504
TypeError: Cannot read property 'length' of undefined
```

After upgrading to the latest version then the error is no longer the same but now the error is
`TypeError: Cannot read property 'title_disk_safe' of undefined`

I am trying to download `1677913611`

![image](https://user-images.githubusercontent.com/67640628/167044446-2053c97c-44bf-4a4d-95e3-d11aa57ecb80.png)

**Comment by ErenKrt** [comment]
Hello again, first of all, thank you very much for your support in the development of the project. I fixed the bug in the current version. You can update and try.

**Comment by DimaSheiko** [comment]
It is nothing, thanks to you for creating this package. It really helps a lot especially downloading all the dependencies. I have updated and indeed the problem is solved. Thank you very much!
